name: Deploy Frontend to cPanel

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        
    - name: Verify build output
      run: |
        if [ ! -d "out" ]; then
          echo "❌ Build output directory 'out' not found!"
          exit 1
        fi
        echo "✅ Build output directory found"
        ls -la out/
        
    - name: Copy .htaccess to build output
      run: |
        if [ -f ".htaccess" ]; then
          cp .htaccess out/.htaccess
          echo "✅ .htaccess copied successfully"
        else
          echo "❌ .htaccess file not found in root directory"
          exit 1
        fi
        
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.CPANEL_SERVER }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./out/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/README.md
          **/.gitignore
          **/components.json
          **/postcss.config.mjs
          **/tailwind.config.ts
          **/next.config.ts
          **/next.config.js
          **/tsconfig*
          **/package-lock.json
          **/public/**
          **/src/**
          **/.eslintrc.json
          **/next-env.d.ts
          **/eslint.config.mjs 